### ISSUE TITLE
webRTCMultipleRoutesEnabled is deprecated since Chrome 48

### ISSUE THREAD

**Issue by A0dh** [aghorler/WebRTC-Leak-Prevent#5]
`privacy.network.webRTCIPHandlingPolicy` should be used instead

Ref: https://developer.chrome.com/extensions/privacy

**Comment by aghorler** [comment]
Refer to [README.md](https://github.com/aghorler/WebRTC-Leak-Prevent#how-it-works).

In **Chromium version 48+**, the extension provides user control over `webRTCIPHandlingPolicy`, defaulting to `default_public_interface_only`.

In older versions of Chromium, legacy options are supported. This includes `webRTCMultipleRoutesEnabled` for **Chromium version 42 - 47**, and `webRTCNonProxiedUdpEnabled` for **Chromium version 47**.

To clarify, `webRTCMultipleRoutesEnabled` is used only if the version of Chrome is below 48.
