### ISSUE TITLE
Не работает WebRTC-Leak-Prevent

### ISSUE THREAD

**Issue by Romikod** [aghorler/WebRTC-Leak-Prevent#7]
WebRTC Leak Prevent не работает в Google Hrome, перепробовал все настройки. Что делать???

**Comment by aghorler** [comment]
What tool are you using to check for WebRTC leaks, and what is the result?

_(I don't speak Russian)._

**Comment by TraderStf** [comment]
https://translate.google.com/
WebRTC Leak Prevent "does not work in Google Chrome, tried all the settings. What to do???"

**Comment by TraderStf** [comment]
https://leaktest.online
https://ipleak.net/
https://browserleaks.com - https://browserleaks.com/webrtc
https://whoer.net/

**Comment by aghorler** [comment]
Yes, I translated it. I just wanted to be clear that some detail may be lost in machine translation.

Can you test using [this tool](https://diafygi.github.io/webrtc-ips/), and *default* **and** *force proxy* option in the extension.

Thanks.

**Comment by Romikod** [comment]
I say that WebRTC-Leak-Prevent does not work in Google Hrome, tried all three modes in the settings, the icon remains inactive.


>Суббота, 25 ноября 2017, 12:17 +03:00 от Aaron Horler <notifications@github.com>:
>
>Yes, I translated it. I just wanted to be clear that some detail may be lost in machine translation.
>Can you test using  this tool , and  default and force proxy option in the extension.
>Thanks.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Roman Astapenko
romikod@bk.ru

**Comment by aghorler** [comment]
>the icon remains inactive

The icon will always be inactive, because I've not bound any functionality to it (press to disable, for example).

Can you test for leaks [here](https://diafygi.github.io/webrtc-ips/), and report the result?

If this issue report is a result of the inactive (greyed out) icon solely, I may assign a simple functionality to the icon (like opening the options page) to reduce confusion.

**Comment by Romikod** [comment]
Then how to find out if WebRTC-Leak-Prevent is working or not working?


>Воскресенье, 26 ноября 2017, 2:50 +03:00 от Aaron Horler <notifications@github.com>:
>
>>the icon remains inactive
>The icon will always be inactive, because I've not bound any functionality to it (press to disable, for example).
>Can you test for leaks  here , and report the result?
>If this issue report is a result of the inactive (greyed out) icon solely, I may assign a simple functionality to the icon (like opening the options page) to reduce confusion.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Roman Astapenko
romikod@bk.ru

**Comment by aghorler** [comment]
It should always be working.

Use the test I linked to.

**Comment by Romikod** [comment]
I do not understand, give me a link to the test.


>Воскресенье, 26 ноября 2017, 16:59 +03:00 от Aaron Horler <notifications@github.com>:
>
>It should always be working.
>Use the test I linked to.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Roman Astapenko
romikod@bk.ru

**Comment by aghorler** [comment]
**https://diafygi.github.io/webrtc-ips/**

Sorry. I was hyperlinking to it on GitHub. I didn't realise that hyperlinks are removed from emails.

**Comment by aghorler** [comment]
I've released a new version in which I've bound the open options functionality to the toolbar icon. This will mean that the icon will no longer be greyed out, and will hopefully reduce confusion.

I've received at least one direct correspondence (in addition to this issue) asking about the icon.

I'll wait for the reporter of this issue to run the @diafygi test, and close the issue.

**Comment by aghorler** [comment]
Closing because result of test has not been reported.
