### ISSUE TITLE
Doesn't work on a specific site

### ISSUE THREAD

**Issue by naldonaldo** [aghorler/WebRTC-Leak-Prevent#8]
Hi,
in https://www.cleancss.com/router-default you can go in a router page and you wil see your private ip.

For example: https://www.cleancss.com/router-default/TP-Link

Same thing with Firefox and a similar plugin.

p.s. In all other test sites I tryed worked well, maybe this site uses something else leak?

**Comment by aghorler** [comment]
In my case, it only shows my local IP address and the local IP addresses of some virtual adapters.

Unfortunately, there's nothing that can be done by extension developers about this. Google must address this themselves.
